// Couleurs officielles des langages de programmation
export const LANGUAGE_COLORS: Record<string, string> = {
  'JavaScript': '#f7df1e',
  'TypeScript': '#3178c6',
  'Python': '#3776ab',
  'Java': '#ed8b00',
  'C++': '#00599c',
  'C': '#a8b9cc',
  'C#': '#239120',
  'PHP': '#777bb4',
  'Ruby': '#cc342d',
  'Go': '#00add8',
  'Rust': '#000000',
  'Swift': '#fa7343',
  'Kotlin': '#7f52ff',
  'Dart': '#0175c2',
  'Scala': '#dc322f',
  'R': '#276dc3',
  'HTML': '#e34c26',
  'CSS': '#1572b6',
  'SCSS': '#c6538c',
  'Sass': '#c6538c',
  'Less': '#1d365d',
  'Vue': '#4fc08d',
  'React': '#61dafb',
  'Angular': '#dd0031',
  'Shell': '#89e051',
  'PowerShell': '#012456',
  'Bash': '#89e051',
  'JSON': '#000000',
  'YAML': '#cb171e',
  'Markdown': '#083fa1',
  'Dockerfile': '#2496ed',
  'SQL': '#336791',
  'TSX': '#3178c6',
  'JSX': '#f7df1e',
  'CoffeeScript': '#244776',
  'Elixir': '#4e2a8e',
  'Haskell': '#5e5086',
  'Lua': '#000080',
  'Perl': '#39457e',
  'Clojure': '#5881d8',
  'Erlang': '#a90533',
  'OCaml': '#3be133',
  'MATLAB': '#e16737',
  'Objective-C': '#438eff',
  'TeX': '#3d6117',
  'Vim script': '#199f4b',
  'Makefile': '#427819',
  'CMake': '#064f8c',
  'Assembly': '#6e4c13',
  'Other': '#6b6b6b',
};

// URLs des icônes des langages (utilisant shields.io ou simple-icons)
export const getLanguageIcon = (language: string): string => {
  const languageMap: Record<string, string> = {
    'JavaScript': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
    'TypeScript': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    'Python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    'Java': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
    'C++': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
    'C': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg',
    'C#': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
    'PHP': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg',
    'Ruby': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg',
    'Go': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg',
    'Rust': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-plain.svg',
    'Swift': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg',
    'Kotlin': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg',
    'HTML': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
    'CSS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
    'SCSS': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
    'Sass': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
    'Vue': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
    'React': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    'Angular': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg',
    'Shell': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg',
    'Bash': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg',
    'Dockerfile': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
    'SQL': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
    'TSX': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    'JSX': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
  };

  return languageMap[language] || `https://img.shields.io/badge/${encodeURIComponent(language)}-gray?style=flat-square&logo=${encodeURIComponent(language.toLowerCase())}`;
};

export const getLanguageColor = (language: string): string => {
  return LANGUAGE_COLORS[language] || LANGUAGE_COLORS['Other'];
};

